version: '3.9'
services:
  postgres:
    image: postgres:alpine3.22
    container_name: ${POSTGRES_CONTAINER_NOME}
    restart: unless-stopped
    en_file: .env
    enviromnment:
      POSTGRES_USER: ${POSTGRES_USER} 
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:5432"
      # Isso faz com que, mesmo se o container for stoppado, ele ainda vai conter os dados pq o volume é persistente
    volumes:
      - postgres_data:/var/lib/postgresql/data
      # Pra não aparecer uma rede default, mas sim a rede custom né
    networks:
      - ecommerce_network
    healthcheck:
      test: ["CMD-SHELL", "pg_ok -U ${POSTGRES_USER}"] # Teste para ver se o container está bom com o DB
      interval: 10s 
      timeout: 5s
      retries: 5

    # Hora do backend
  api: 
    # Vai construir a imagem do Docker a partir do Dockerfile localizado no diretório ./api
    build:
      context: ./api # Contexto é onde o Dockerfile está localizado
    container_name: ${API_CONTAINER_NAME}
    restart: unless-stopped
    env_file: .env
    environment:
      # DATABASE_URL é a variável de ambiente que a aplicação vai usar para se conectar ao banco de dados
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:${POSTGRES_PORT}/${POSTGRES_DB}
      NODE_ENV: ${NODE_ENV}
    ports:
      - "${API_PORTA}:3000"
    volumes:
      - ./api:/app
      - /app/node_modules
      - ./api/logs:/app/logs
    depends_on:
      postgres:
        condition: service_healthy